# Generated by Django 5.2.7 on 2025-11-12 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('contato', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
            ],
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
            ],
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('progresso', models.DecimalField(blank=True, decimal_places=2, help_text='Progresso em %', max_digits=5, null=True)),
                ('curso_turma', models.CharField(blank=True, max_length=200)),
                ('alunos', models.TextField(blank=True, help_text='Lista de alunos participantes')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('anexos', models.TextField(blank=True, help_text='URLs ou descrições dos anexos')),
                ('empresa_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_empresa', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.IntegerField(default=0, help_text='Posição ou prioridade do destaque')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_entries', to='app.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Grupo I'), ('II', 'Grupo II')], max_length=10)),
                ('projetos', models.ManyToManyField(blank=True, related_name='grupos', to='app.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='projetos_associados',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='app.projeto'),
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True)),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Em análise', max_length=100)),
                ('anexos', models.TextField(blank=True, help_text='URLs ou descrições dos anexos da proposta')),
                ('empresa', models.ForeignKey(help_text='Empresa que enviou a proposta', on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='proposta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='app.proposta'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_aprovados', to='app.coordenador'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='coordenadores', to='app.projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsaveis', to='app.professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='professores', to='app.projeto'),
        ),
    ]
