# Generated by Django 5.2.7 on 2025-10-29 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('contato', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('progresso', models.CharField(blank=True, max_length=100)),
                ('curso_turma', models.CharField(blank=True, max_length=200)),
                ('alunos', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('etapa_atual', models.IntegerField(blank=True, null=True)),
                ('etapa_final', models.IntegerField(blank=True, null=True)),
                ('etapa_total', models.IntegerField(blank=True, null=True)),
                ('anexos', models.TextField(blank=True, help_text='URLs ou descrições dos anexos')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_aprovados', to='app.coordenacao')),
                ('empresa_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='app.empresa')),
                ('professor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='app.professor')),
                ('projetos_vinculados', models.ManyToManyField(blank=True, related_name='projetos_vinculantes', to='app.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.IntegerField(default=0, help_text='Posição ou prioridade do destaque')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_entries', to='app.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Grupo I'), ('II', 'Grupo II')], max_length=10)),
                ('projetos', models.ManyToManyField(blank=True, related_name='grupos', to='app.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='app.usuario'),
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diretor', to='app.usuario')),
            ],
        ),
    ]
